FROM java:8
VOLUME /tmp
ADD WS4-Authentication.jar WS4-Authentication.jar
EXPOSE 8080
RUN bash -c 'touch /WS4-Authentication.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/WS4-Authentication.jar"]